spring:
    profiles:
        active: dev
    datasource:
        driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://backend_db:3306/backend?useUnicode=true&characterEncoding=utf8
        name:
        username: root
        password: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        show_sql: true
        hibernate:
            naming:
              implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
custom:
    secretKey: changeme
    accessTokenValidityInSeconds: 300
    refreshTokenValidityInSeconds: 3600
    storageFolder: /home/docker/app/storage
    datasource:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
